### ISSUE TITLE
How to locate center preview message?

### ISSUE THREAD

**Issue by iRusel** [cyberalien/phpbb31_styles#1]
Tell me how to do that was in the middle?

Screenshot: 
http://s7.hostingkartinok.com/uploads/images/2015/03/077241aacc7e51e8c9c87c128b9fa827.png

Sorry for my bad english.

**Comment by cyberalien** [comment]
Thanks for reporting, I'll fix that. Bug happens in post preview only when profile is located on left side.

**Comment by cyberalien** [comment]
Fixed: https://github.com/cyberalien/phpbb31_styles/commit/eefc07144d54e70a0580979bcbf3099a73d210de

It will be included in version 1.0.2 that I'll release in few days.
