### ISSUE TITLE
Nav topics in footer.

### ISSUE THREAD

**Issue by iRusel** [cyberalien/phpbb31_styles#2]
![2015-04-22 18-52-23 styles demo digi - google chrome](https://cloud.githubusercontent.com/assets/5162861/7278878/d1ee60b2-e920-11e4-93e3-37722da735bc.png)

**Comment by iRusel** [comment]
Fix: https://github.com/cyberalien/phpbb31_styles/compare/styles/digi...iRusel:patch-1

**Comment by cyberalien** [comment]
Its not a bug, its normal behavior for phpBB. Links block in footer has many other links, its not a copy of top breadcrumbs. Most of them are visible only to registered users, so they aren't shown on demo.
