### ISSUE TITLE
PHPBB 3.2x

### ISSUE THREAD

**Issue by Mtechnik** [cyberalien/phpbb31_styles#5]
Was wondering if youd start on the next released version of phpbb3.2. Ive already installed it and currently using the Elegance style. All works perfectly fine except for the buttons. The only buttons that seems to work properly while viewing a forum topic is the Reply button. But the Print Topic and Subscribe button drop down seems to be missing languages or something Idk It just shows up as a dropdown with 0 square shapes in them as if it was a language problem or something but I cannot find where I could edit that either.

**Comment by cyberalien** [comment]
I'll wait until 3.2 is in RC stage before working on updating styles.
